services:
  - type: web
    name: opengravity
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ALLOWED_USER_IDS
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: WEBHOOK_URL
        value: "https://opengravity-xky8.onrender.com"

      - key: OPENROUTER_MODEL
        value: "openrouter/free"
      - key: DB_PATH
        value: "./memory.db"

